/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package stockmanagement;
import java.io.FileOutputStream;
import java.util.Date;

import com.itextpdf.text.Anchor;
import com.itextpdf.text.BadElementException;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chapter;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.List;
import com.itextpdf.text.ListItem;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.Section;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.File;
/**
 *
 * @author Yuvi
 */
public class GenPDF {

     private static String FILE = "D:/InvoicePdf.pdf";
  private static Font catFont = new Font(Font.FontFamily.TIMES_ROMAN, 18,
      Font.BOLD);
  private static Font redFont = new Font(Font.FontFamily.TIMES_ROMAN, 12,
      Font.NORMAL, BaseColor.RED);
  private static Font subFont = new Font(Font.FontFamily.TIMES_ROMAN, 16,
      Font.BOLD);
  private static Font smallBold = new Font(Font.FontFamily.TIMES_ROMAN, 12,
      Font.BOLD);

   public GenPDF(StringBuilder sb)
   {
       try{
        File f=  new File(FILE);
      f.createNewFile();
      Document document = new Document();
      PdfWriter.getInstance(document, new FileOutputStream(f));
      document.open();
    addContent(document,sb);
     document.close();
       }catch(Exception e){e.printStackTrace();}
   }

  

  private static void addContent(Document document,StringBuilder sb) throws DocumentException {
    Anchor anchor = new Anchor("Invoice", catFont);
    anchor.setName("Invoice");

    // Second parameter is the number of the chapter
    Paragraph subPara = new Paragraph("Invoice         Dated : "+new Date(), subFont);
    subPara.add(new Paragraph(sb.toString()));
   
    document.add(subPara);
    document.add(new Paragraph("Report generated by: " + System.getProperty("user.name") + ", " + new Date(), //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$
        smallBold));

  }



}

