/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package stockmanagement;

import javax.swing.JFrame;

/**
 *
 * @author Stalwart
 */
public class Task extends javax.swing.JPanel {

    /**
     * Creates new form Task
     */
    public Task() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btCheckOfStock = new javax.swing.JButton();
        btBillling = new javax.swing.JButton();
        btUpdate = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24));
        jLabel1.setForeground(new java.awt.Color(0, 102, 153));
        jLabel1.setText("TASK");

        btCheckOfStock.setText("CheckOfStock");
        btCheckOfStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCheckOfStockActionPerformed(evt);
            }
        });

        btBillling.setText("Billing");
        btBillling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBilllingActionPerformed(evt);
            }
        });

        btUpdate.setText("UpdateOfStock");
        btUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btBillling)
                            .addComponent(btCheckOfStock)
                            .addComponent(btUpdate)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel1)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(btCheckOfStock)
                .addGap(26, 26, 26)
                .addComponent(btBillling)
                .addGap(29, 29, 29)
                .addComponent(btUpdate)
                .addContainerGap(28, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btCheckOfStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCheckOfStockActionPerformed
        JFrame fr=new JFrame();
            fr.add( new CheckOfStock());
            fr.setSize(700,500);
            fr.setVisible(true);
    }//GEN-LAST:event_btCheckOfStockActionPerformed

    private void btBilllingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBilllingActionPerformed
        JFrame fr=new JFrame();
            fr.add( new Billing());
            fr.setSize(400,400);
            fr.setVisible(true);
    }//GEN-LAST:event_btBilllingActionPerformed

    private void btUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUpdateActionPerformed
     
            new InvoiceDetails().setVisible(true);
    }//GEN-LAST:event_btUpdateActionPerformed

              
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBillling;
    private javax.swing.JButton btCheckOfStock;
    private javax.swing.JButton btUpdate;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}

                
